#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_jp/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8707)         += touch_ft8707.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8707)         += touch_ft8707_prd.o
#obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8707)         += fts/

