#
# Makefile for the e-pack drivers
#


obj-$(CONFIG_INPUT_EPACK)	+= epack_core.o
obj-$(CONFIG_INPUT_EPACK)	+= cmd.o
obj-$(CONFIG_INPUT_EPACK)	+= I2CMain.o
#obj-$(CONFIG_INPUT_EPACK)	+= Driver/DrvI2C.o
obj-$(CONFIG_INPUT_EPACK)	+= epack_audio.o
obj-$(CONFIG_INPUT_EPACK)	+= epack_power.o