#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)         += touch_ft8607.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)         += touch_ft8607_prd.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)         += fts/

