# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_jp/

obj-y +=  focaltech_ctl.o focaltech_ex_fun.o focaltech_flash.o

#focaltech_gesture.o 
#extlibs :=$(PWD)/drivers/input/touchscreen/ft_gesture_32bit_lib_v1.0_20140820.a 
#ldflagobj-y += fts_ts.o 
#obj-y s-y +=--whole-archive $(extlibs) --no-whole-archive

