
ifeq ($(CONFIG_TOUCHSCREEN_MSM8952_P1V), y)
obj-y 	+= ver_3_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8937_PH2), y)
obj-y 	+= ver_3_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8916_C70), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8939_P1B), y)
obj-y 	+= ver_3_0/
endif

ifeq ($(CONFIG_MSM8916_C90), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_MTK_TD4191),y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_LU201X), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_LU201X), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_FOCALTECH), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_LU201X), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_LGE_MELFAS), y)
obj-y 	+= ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8916_YG), y)
obj-y   += ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8916_C100N), y)
obj-y   += ver_2_0/
endif
