ifeq ($(CONFIG_MACH_MSM8937_LGPS29),y)
DTS_TARGET := msm8937-lgps29
endif

ifeq ($(CONFIG_MACH_MSM8940_LGPS33),y)
DTS_TARGET := msm8940-lgps33
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_SPR_US),y)
DTS_TARGET := msm8940-sf3_spr_us
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_TMO_US),y)
DTS_TARGET := msm8940-sf3_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8940_TF8_TMO_US),y)
DTS_TARGET := msm8940-tf8_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_MPCS_US),y)
DTS_TARGET := msm8940-sf3_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8937_PH2_GLOBAL_COM),y)
DTS_TARGET := msm8937-ph2_global_com
endif

ifeq ($(CONFIG_MACH_MSM8937_PH2_CMO_CN),y)
DTS_TARGET := msm8937-ph2_cmo_cn
endif

ifeq ($(CONFIG_MACH_MSM8937_PH2N_TMO_US),y)
DTS_TARGET := msm8937-ph2n_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8937_PH2N_MPCS_US),y)
DTS_TARGET := msm8937-ph2n_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8937_PH2N_GLOBAL_CA),y)
DTS_TARGET := msm8937-ph2n_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8937_L5_DCM_JP),y)
DTS_TARGET := msm8937-l5_dcm_jp
endif

ifeq ($(CONFIG_MACH_MSM8937_JSG_KDDI_JP),y)
DTS_TARGET := msm8937-JSG_kddi_jp
endif

ifeq ($(CONFIG_MACH_MSM8917_LGPS29_1),y)
DTS_TARGET := msm8917-lgps29_1
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_MPCS_US),y)
DTS_TARGET := msm8917-lv3_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_TMO_US),y)
DTS_TARGET := msm8917-lv3_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_USC_US),y)
DTS_TARGET := msm8917-lv3_usc_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_LGU_KR),y)
DTS_TARGET := msm8917-lv3_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_SKT_KR),y)
DTS_TARGET := msm8917-lv3_skt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_KT_KR),y)
DTS_TARGET := msm8917-lv3_kt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_GLOBAL_COM),y)
DTS_TARGET := msm8917-lv3_global_com
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_TRF_US),y)
DTS_TARGET := msm8917-lv7_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_TRF_US_VZW),y)
DTS_TARGET := msm8917-lv7_trf_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_CCT_US_VZW),y)
DTS_TARGET := msm8917-lv7_cct_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_CRK_US),y)
DTS_TARGET := msm8917-lv7_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_GLOBAL_CA),y)
DTS_TARGET := msm8917-lv7_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8917_B6_JCM_JP),y)
DTS_TARGET := msm8917-b6_jcm_jp
endif

ifeq ($(CONFIG_MACH_MSM8917_B6_LGU_KR),y)
DTS_TARGET := msm8917-b6_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517N_ATT_US),y)
DTS_TARGET := msm8917-lv517n_att_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_CRK_US),y)
DTS_TARGET := msm8917-lv517_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_TMO_US),y)
DTS_TARGET := msm8917-lv517_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_MPCS_US),y)
DTS_TARGET := msm8917-lv517_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_TRF_US),y)
DTS_TARGET := msm8917-lv517_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_VZW),y)
DTS_TARGET := msm8917-lv517_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_TRF_US),y)
DTS_TARGET := msm8917-sf317_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_TRF_US_VZW),y)
DTS_TARGET := msm8917-sf317_trf_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_CRK_US),y)
DTS_TARGET := msm8917-sf317_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_ATT_US),y)
DTS_TARGET := msm8940-lv9_att_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_NAO_US),y)
DTS_TARGET := msm8940-lv9_nao_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_GLOBAL_COM),y)
DTS_TARGET := msm8940-lv9_global_com
endif

ALL_DTS := $(notdir $(wildcard echo $(srctree)/$(src)/$(DTS_TARGET)/*.dts))
dtb-y += $(patsubst %.dts,%.dtb,$(ALL_DTS))

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

ifeq ($(CONFIG_ARM64),y)
always  := $(addprefix ../,$(DTB_LIST))

$(obj)/../%.dtb: $(src)/$(DTS_TARGET)/%.dts FORCE
	$(call if_changed_dep,dtc)
else
targets += dtbs
targets += $(addprefix ../, $(DTB_LIST))

$(obj)/../%.dtb: $(src)/$(DTS_TARGET)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/$(DTS_TARGET)/,$(DTB_LIST))
endif

clean-files := *.dtb
